### ISSUE TITLE
run ends with empty result fasta files

### ISSUE THREAD

**Issue by splaisan** [JianjunJin/Traversome#24] opened 2024-04-05 08:14 UTC
Hi @JianjunJin,

After installing GraphAligner (v1.0.13-) and traversome, I tried traversome on my gfa and ONT long read data of a mixture of several phage genomes.

I get three empty sequences out of the traversome run but no error reported.

Do you have any idea what could be fixed to get better results?
I cannot share the sequences publicly but if you give me a private link I can share with you.

thanks in advance for your help

```
GraphAligner -g assembly_graph.gfa -f ont_reads.fg.gz -a output_align.gaf -x vg

GraphAligner bioconda 1.0.13-
Load graph from assembly_graph.gfa
Build alignment graph
Build minimizer seeder from the graph
Minimizer seeds, length 15, window size 20, density 10
Seed cluster size 1
Alignment bandwidth 10
Clip alignment ends with identity < 66%
X-drop DP score cutoff 14705
write alignments to phi315_align.gaf
Align
Alignment finished
Input reads: 275 (10007905bp)
Seeds found: 2266938
Seeds extended: 2761
Reads with a seed: 275 (10007905bp)
Reads with an alignment: 275 (9560761bp)
Alignments: 2696 (76540021bp) (65 additional alignments discarded)
End-to-end alignments: 0 (0bp)
```

```
traversome thorough -g assembly_graph.gfa -a output_align.gaf -o outdir --topo circular --chr all
```

[traversome.log.txt](https://github.com/JianjunJin/Traversome/files/14882014/traversome.log.txt)

**Comment by JianjunJin** [comment] 2024-04-10 11:45
Hi @splaisan 
Thanks for trying Traversome! The result so far looks promising! Sorry that I don't know why it's getting no seqs.
Please send me the graph (`assembly_graph.gfa`) and the graph alignment (`output_align.gaf`) to jianjun.jin@columbia.edu if it sounds good to you. I can test it for you and will not share it to anyone.

**Comment by JianjunJin** [comment] 2024-04-13 02:47
Hi @splaisan 

Thank you for sending me the file. Upon further investigation, I realized that the issue was caused by a bug that had been previously fixed in another branch. This fix has now been merged into the master branch, and the latest version of Traversome, 0.1.4, includes many new features and bug fixes.
Please update Traversome to the latest version and rerun your data using the following command:
```
traversome thorough \
   -g assembly_graph.gfa \
   -a assembly_align.gaf \
   -o issue24-tvs-out \
   --topo circular \
   --v-comp all \
   --min-align-id 0.95 \
   --min-align-counts 20 \
   --ignore-conflicts
```
- `--v-comp` has replaced `--chr` in the newer version.
- `--min-align-id 0.95` filters out alignment records with identities below 0.95.
- `--min-align-counts 20` filters out alignment records with path occurrences below 20. These two filtering parameters are crucial for fine-tuning to obtain a well-supported result. According to our unpublished simulation test, which will be available online soon, results with bootstrap support above 95% are considered reliable.
- `--ignore-conflicts` is used here to complete the analysis despite any detected conflicts between the graph and the alignment. The latest version of Traversome includes a module that detects apparent conflicts between the graph and the alignment based on the distribution of chimeric points. If such conflicts are present, as in this phage dataset, it suggests that the graph may not be the perfect assembly containing all variations found in the alignment (long reads). In other words, while the current result may or may not be accurate, there are likely other variants missing from the graph.

Except for the log file attached here [traversome.log.txt](https://github.com/JianjunJin/Traversome/files/14965024/traversome.log.txt), other detailed results are attached to the private reply email sent to you.

Please let me know if you have any further questions or concerns.

**Closed** 2024-04-15 09:33 UTC

**Comment by JianjunJin** [comment] 2024-04-15 14:45
Sure. And here's what traversome did in brief: it filters out potentially erroneous read alignments, heuristically proposed 15 unique candidates (see `tmp.candidates` for paths of them) based on both the graph and the alignment information, kept two variants out of the 15 candidates using model selection, do 100 replicates of the model selection based on randomly-subsampled read alignments.
